version: "3"

services:
  
  web:
    image: lachlanmarnham/personal_website_production:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

networks:
  backend:
